# Generated by Django 4.2.5 on 2023-09-09 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingapplication',
            name='client',
        ),
        migrations.RemoveField(
            model_name='bookingapplication',
            name='stay_duration',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='bookingapplication',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingapplication',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='cost_per_day',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
